##########################################################################
# Plugins settings
#
# Status: in use
##########################################################################

core.tools.office-documents-converter.outputFormats = pdf pdfa-1a pdfa-1b pdfa-2b pdfa-3b odt ott doc docx rtf txt html xls xlsx csv ods odp ppt pptx svg
core.tools.office-documents-converter.excludedExtensions = cur pict ico dds pfm hdr

core.plugins.conversion.profile.se.whitered.eterna.plugins.officedocumentsconverter.OfficeDocumentsConverter = office-documents-converter
core.plugins.conversion.profile.office-documents-converter.profiles.i18nPrefix = office-documents-converter
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdf
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-1a
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-1b
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-2b
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-3b
core.plugins.conversion.profile.office-documents-converter.profiles[] = odt
core.plugins.conversion.profile.office-documents-converter.profiles[] = ott
core.plugins.conversion.profile.office-documents-converter.profiles[] = doc
core.plugins.conversion.profile.office-documents-converter.profiles[] = docx
core.plugins.conversion.profile.office-documents-converter.profiles[] = rtf
core.plugins.conversion.profile.office-documents-converter.profiles[] = txt
core.plugins.conversion.profile.office-documents-converter.profiles[] = html
core.plugins.conversion.profile.office-documents-converter.profiles[] = xls
core.plugins.conversion.profile.office-documents-converter.profiles[] = xlsx
core.plugins.conversion.profile.office-documents-converter.profiles[] = csv
core.plugins.conversion.profile.office-documents-converter.profiles[] = ods
core.plugins.conversion.profile.office-documents-converter.profiles[] = odp
core.plugins.conversion.profile.office-documents-converter.profiles[] = ppt
core.plugins.conversion.profile.office-documents-converter.profiles[] = pptx
core.plugins.conversion.profile.office-documents-converter.profiles[] = svg

core.tools.office-documents-converter.inputFormatExtensions = pdf doc docx odt ott rtf txt html xls xlsx ods csv ppt pptx odp

core.tools.office-documents-converter.inputFormatMimeTypes = \
 application/msword \
 application/vnd.openxmlformats-officedocument.wordprocessingml.document \
 application/vnd.ms-excel \
 application/vnd.openxmlformats-officedocument.spreadsheetml.sheet \
 application/vnd.ms-powerpoint \
 application/vnd.openxmlformats-officedocument.presentationml.presentation \
 application/vnd.oasis.opendocument.text \
 application/vnd.oasis.opendocument.spreadsheet \
 application/vnd.oasis.opendocument.presentation \
 text/plain text/html \
 application/pdf

core.tools.office-documents-converter.inputFormatPronoms = \
 fmt/40 fmt/412 fmt/18 fmt/214 fmt/215 fmt/216 fmt/291 fmt/292 fmt/293 fmt/91 fmt/92 fmt/413 \
 fmt/14 fmt/15 fmt/16 fmt/17 fmt/276 fmt/19 fmt/20

##########################################################################
# PRONOM ? extension mappings for Office Documents
##########################################################################

core.tools.pronom.fmt/40 = doc
core.tools.pronom.fmt/412 = docx
core.tools.pronom.fmt/18 = xls
core.tools.pronom.fmt/214 = xlsx
core.tools.pronom.fmt/215 = ppt
core.tools.pronom.fmt/216 = pptx
core.tools.pronom.fmt/291 = odt
core.tools.pronom.fmt/292 = ods
core.tools.pronom.fmt/293 = odp
core.tools.pronom.fmt/91 = svg
core.tools.pronom.fmt/92 = svg
core.tools.pronom.fmt/413 = svg
core.tools.pronom.fmt/14 = pdf
core.tools.pronom.fmt/15 = pdf
core.tools.pronom.fmt/16 = pdf
core.tools.pronom.fmt/17 = pdf
core.tools.pronom.fmt/276 = pdf
core.tools.pronom.fmt/19 = pdf
core.tools.pronom.fmt/20 = pdf




core.plugins.conversion.profile.office-documents-converter.pdf.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdf.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-1a.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-1a.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-1b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-1b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-2b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-2b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-3b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-3b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.odt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.odt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ott.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ott.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.doc.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.doc.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.docx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.docx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.rtf.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.rtf.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.txt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.txt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.html.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.html.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.xls.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.xls.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.xlsx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.xlsx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.csv.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.csv.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ods.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ods.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.odp.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.odp.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ppt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ppt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pptx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pptx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.svg.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.svg.canBeUsedForRepresentation = true


