##########################################################################
# Plugins settings
#
# Status: in use
##########################################################################

#core.tools.office-documents-converter.inputFormatExtensions = afi apng bmp bpx btf cog cur dcx ddb dds dib dng gif hdr icb icns ico jfi jfif jif jpe jpeg jpg pam pbm pcc pct pcx pdd pfm pgm pgma pgmb pic pict png ppm ppmb psb psd sgi spf svg svgz tf8 tfx tga tif tiff vda vst wbmp webp xdm xwd
#core.tools.office-documents-converter.inputFormatMimeTypes = image/bmp image/dng image/gif image/jpeg image/pfm image/png image/svg+xml image/tiff image/vnd-wap-wbmp image/vnd.adobe.photoshop image/vnd.microsoft.icon image/vnd.mozilla.apng image/vnd.radiance image/vnd.zbrush.pcx image/webp image/x-dcx image/x-icon image/x-macpaint image/x-pict image/x-portable-anymap image/x-portable-bitmap image/x-portable-graymap image/x-portable-pixmap image/x-sgi image/x-targa image/x-tga image/x-tiff-big image/x-win-bitmap image/x-xwindowdump
#core.tools.office-documents-converter.inputFormatPronoms = fmt/3 fmt/4 fmt/11 fmt/12 fmt/13 fmt/41 fmt/42 fmt/43 fmt/44 fmt/86 fmt/87 fmt/88 fmt/89 fmt/90 fmt/91 fmt/92 fmt/112 fmt/114 fmt/115 fmt/116 fmt/117 fmt/118 fmt/119 fmt/152 fmt/153 fmt/154 fmt/155 fmt/156 fmt/341 fmt/353 fmt/385 fmt/401 fmt/402 fmt/405 fmt/406 fmt/407 fmt/408 fmt/413 fmt/497 fmt/566 fmt/567 fmt/568 fmt/591 fmt/645 fmt/935 fmt/996 fmt/1040 fmt/1185 fmt/1507 fmt/1917 x-fmt/80 x-fmt/92 x-fmt/109 x-fmt/119 x-fmt/140 x-fmt/164 x-fmt/178 x-fmt/209 x-fmt/270 x-fmt/300 x-fmt/348 x-fmt/367 x-fmt/387 x-fmt/388 x-fmt/390 x-fmt/391 x-fmt/398 x-fmt/399 x-fmt/418
core.tools.office-documents-converter.outputFormats = pdf pdfa-1a pdfa-1b pdfa-2b pdfa-3b odt ott doc docx rtf txt html xls xlsx csv ods odp ppt pptx svg
core.tools.office-documents-converter.excludedExtensions = cur pict ico dds pfm hdr

#core.tools.pronom.fmt/3 = gif
#core.tools.pronom.fmt/4 = gif
#core.tools.pronom.fmt/11 = png
#core.tools.pronom.fmt/12 = png
#core.tools.pronom.fmt/13 = png
#core.tools.pronom.fmt/41 = jpe jpg jpeg jif jfif jfi
#core.tools.pronom.fmt/42 = jpeg jpe jpg jif jfif jfi
#core.tools.pronom.fmt/43 = jpg jpe jpeg jif jfif jfi
#core.tools.pronom.fmt/44 = jpg jpe jpeg jif jfif jfi
#core.tools.pronom.fmt/86 = pcx pcc
#core.tools.pronom.fmt/87 = pcx pcc
#core.tools.pronom.fmt/88 = pcx pcc
#core.tools.pronom.fmt/89 = pcx pcc
#core.tools.pronom.fmt/90 = pcx pcc
#core.tools.pronom.fmt/91 = svg
#core.tools.pronom.fmt/92 = svg
#core.tools.pronom.fmt/112 = spf jpg
#core.tools.pronom.fmt/114 = ddb bmp
#core.tools.pronom.fmt/115 = bmp dib
#core.tools.pronom.fmt/116 = dib bmp
#core.tools.pronom.fmt/117 = dib bmp
#core.tools.pronom.fmt/118 = bmp dib
#core.tools.pronom.fmt/119 = bmp dib
#core.tools.pronom.fmt/152 = dng tif tiff
#core.tools.pronom.fmt/153 = tif tiff
#core.tools.pronom.fmt/154 = tif tiff
#core.tools.pronom.fmt/155 = tif tiff cog
#core.tools.pronom.fmt/156 = tif tiff tfx
#core.tools.pronom.fmt/341 = pct pict pic
#core.tools.pronom.fmt/353 = tif tiff
#core.tools.pronom.fmt/385 = cur
#core.tools.pronom.fmt/401 = xwd xdm
#core.tools.pronom.fmt/402 = tga icb vda vst
#core.tools.pronom.fmt/405 = pam
#core.tools.pronom.fmt/406 = pgmb pgm
#core.tools.pronom.fmt/407 = pgma pgm
#core.tools.pronom.fmt/408 = ppm ppmb
#core.tools.pronom.fmt/413 = svg
#core.tools.pronom.fmt/497 = wbmp
#core.tools.pronom.fmt/566 = webp
#core.tools.pronom.fmt/567 = webp
#core.tools.pronom.fmt/568 = webp
#core.tools.pronom.fmt/591 = hdr
#core.tools.pronom.fmt/645 = jpg jpeg
#core.tools.pronom.fmt/935 = png apng
#core.tools.pronom.fmt/996 = psb
#core.tools.pronom.fmt/1040 = dds
#core.tools.pronom.fmt/1185 = icns
#core.tools.pronom.fmt/1507 = jpg jpeg
#core.tools.pronom.fmt/1917 = tif tf8 btf
#core.tools.pronom.x-fmt/80 = pct pict
#core.tools.pronom.x-fmt/92 = psd pdd
#core.tools.pronom.x-fmt/109 = svgz
#core.tools.pronom.x-fmt/140 = sgi
#core.tools.pronom.x-fmt/164 = pbm
#core.tools.pronom.x-fmt/178 = ppm
#core.tools.pronom.x-fmt/209 = xwd
#core.tools.pronom.x-fmt/270 = bmp
#core.tools.pronom.x-fmt/300 = xdm xwd
#core.tools.pronom.x-fmt/348 = dcx
#core.tools.pronom.x-fmt/367 = tga icb vda vst afi bpx
#core.tools.pronom.x-fmt/387 = tif tiff
#core.tools.pronom.x-fmt/388 = tif tiff
#core.tools.pronom.x-fmt/390 = jpg jpeg
#core.tools.pronom.x-fmt/391 = jpg jpeg
#core.tools.pronom.x-fmt/398 = jpg jpeg
#core.tools.pronom.x-fmt/399 = tif tiff
#core.tools.pronom.x-fmt/418 = ico

core.plugins.conversion.profile.org.roda.core.plugins.external.OfficeDocumentsConverter = office-documents-converter
core.plugins.conversion.profile.office-documents-converter.profiles.i18nPrefix = office-documents-converter
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdf
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-1a
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-1b
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-2b
core.plugins.conversion.profile.office-documents-converter.profiles[] = pdfa-3b
core.plugins.conversion.profile.office-documents-converter.profiles[] = odt
core.plugins.conversion.profile.office-documents-converter.profiles[] = ott
core.plugins.conversion.profile.office-documents-converter.profiles[] = doc
core.plugins.conversion.profile.office-documents-converter.profiles[] = docx
core.plugins.conversion.profile.office-documents-converter.profiles[] = rtf
core.plugins.conversion.profile.office-documents-converter.profiles[] = txt
core.plugins.conversion.profile.office-documents-converter.profiles[] = html
core.plugins.conversion.profile.office-documents-converter.profiles[] = xls
core.plugins.conversion.profile.office-documents-converter.profiles[] = xlsx
core.plugins.conversion.profile.office-documents-converter.profiles[] = csv
core.plugins.conversion.profile.office-documents-converter.profiles[] = ods
core.plugins.conversion.profile.office-documents-converter.profiles[] = odp
core.plugins.conversion.profile.office-documents-converter.profiles[] = ppt
core.plugins.conversion.profile.office-documents-converter.profiles[] = pptx
core.plugins.conversion.profile.office-documents-converter.profiles[] = svg

core.plugins.conversion.profile.office-documents-converter.pdf.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdf.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-1a.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-1a.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-1b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-1b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-2b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-2b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pdfa-3b.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pdfa-3b.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.odt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.odt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ott.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ott.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.doc.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.doc.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.docx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.docx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.rtf.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.rtf.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.txt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.txt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.html.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.html.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.xls.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.xls.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.xlsx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.xlsx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.csv.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.csv.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ods.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ods.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.odp.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.odp.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.ppt.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.ppt.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.pptx.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.pptx.canBeUsedForRepresentation = true

core.plugins.conversion.profile.office-documents-converter.svg.canBeUsedForDissemination = true
core.plugins.conversion.profile.office-documents-converter.svg.canBeUsedForRepresentation = true


